# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do
    before_all do
        
    end
    
    desc "Bumps build number and runs unit tests on each push to development branch"
    desc "If successful, pushes the bumped version to git"
    lane :development do
        ensure_git_branch(branch: ENV["DEVELOPMENT_BRANCH"])
        ensure_git_status_clean
        
#        update_graph

        #sh "cd .. && carthage.sh update --use-submodules --use-xcframeworks"
        
        build_spm

        #run_spm_tests

        bump_build_number
        
#        clean_build_artifacts
        
        push_to_git_remote
        
        notify_slack_dev_success
    end

    
    lane :release do
        version = "v" + get_version_number(
                                           xcodeproj: "iOSClientExposure.xcodeproj",
                                           target: "iOSClientExposure"
                                           )
        
        if !git_tag_exists(tag: version)
            
            Action.sh("git branch '#{version}'")
            Action.sh("git checkout '#{version}'")
            
            fix_dependencies
            
            if !Action.sh("git diff --name-only").empty?
                Action.sh("git add -A")
                Action.sh("git commit -m 'Version: #{version}'")
            end
            
            update_graph
            run_unit_tests
            
            add_git_tag(tag: version)
            Action.sh("git push origin --all")
            Action.sh("git push --tags")
            
            current_time = Time.now.to_f
            project_name = ENV["PROJECT_TITLE"]
            
            slack(
                  use_webhook_configured_username_and_icon: true,
                  default_payloads: [],
                  attachment_properties: {
                        pretext: "#{project_name} #{version} released",
                        color: "good",
                        text: "Released!",
                        footer: ENV["DEV_TEAM_NAME"],
                        ts: current_time,
                    }
                  )
        end
    end
    

    desc "Build Xcode project "
    lane :build_xcode_project do

      #fastlane gym --project "iOSClientExposure.xcodeproj" --scheme "iOSClientExposure" --skip_package_ipa true --clean 

      build_app(
        project: "iOSClientExposure.xcodeproj",
        configuration: "Release",
        scheme: "iOSClientExposure",
        silent: true,
        clean: true,
        skip_package_ipa: true
      )
        UI.success("== iOS Project Build Success ==")

      build_app(
        project: "iOSClientExposure.xcodeproj",
        configuration: "Release",
        scheme: "iOSClientExposure-tvOS",
        silent: true,
        clean: true,
        skip_package_ipa: true
      )
        UI.success("== tvOS Project Build Success ==")

     
    end


    desc "Run unit tests"
    lane :run_spm_tests do |options|

      workspace =  "#{options[:workspace]}"
      slackUrl =  "#{options[:slackUrl]}"

        run_tests(
          workspace: '.swiftpm/xcode/package.xcworkspace', # ignore .xcodeproj if it exists
          devices: ['iPhone 13 Pro Max'],
          scheme: 'iOSClientExposure',
          derived_data_path: '#{workspace}/unit_tests',
          slack_url:slackUrl
        )

        UI.success("== iOS Unit tests were Success ==")

         run_tests(
          workspace: '.swiftpm/xcode/package.xcworkspace', # ignore .xcodeproj if it exists
          devices: ['Apple TV'],
          scheme: 'iOSClientExposure-tvOS',
          derived_data_path: '#{workspace}/unit_tests',
          slack_url:slackUrl
        )

        UI.success("== iOS Unit tests were Success ==")

    end

    desc "Validate pod spec"
    lane :validate_pod do
     
      sh 'cd .. && pod lib lint --allow-warnings'
      UI.success("== Pod Validation passed ==")

    end

    desc "Version bump"
    lane :increment_versions do |options|

      bump_type =  "#{options[:bump_type]}"
     
      version = version_bump_podspec(path: "iOSClientExposure.podspec", bump_type: bump_type)

      increment_build_number_in_plist(target: 'iOSClientExposure')
      increment_version_number_in_plist(target: 'iOSClientExposure' ,  bump_type: bump_type )

      commit_version_bump(
        message: "Version Bump",# create a commit with a custom message
         include: %w[iOSClientExposure.podspec]
      )

      UI.success("== Version bump success ==")

    end



    # desc "Build project using spm"
    # lane :run_spm_tests do

    #     # sh 'swift test -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"'
    #     # UI.success("== iOS Project Unit Tests were Success ==")

    #     # sh 'swift test -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk appletvsimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-tvos13.0-simulator"'
    #     # UI.success("== tvOS Project Unit Tests were Success ==")


    # end

    desc "Runs all the tests"
    lane :run_unit_tests do
        
        UI.success("== iOS Unit tests ==")
        scan(
             workspace: ENV["UNIT_TEST_WORKSPACE"],
             scheme: ENV["IOS_UNIT_TEST_SCHEME"]
             )
             
         UI.success("== tvOS Unit tests ==")
         scan(
              workspace: ENV["UNIT_TEST_WORKSPACE"],
              scheme: ENV["TVOS_UNIT_TEST_SCHEME"]
              )
                  
    end
    
    private_lane :fix_dependencies do
        version = "v" + get_version_number(
                                           xcodeproj: ENV["XCODE_PROJECT"],
                                           target: ENV["RELEASE_VERSION_TARGET"]
                                           )
        cartfile = File.expand_path("..",Dir.pwd) + "/Cartfile"
        UI.message(cartfile)
        if File.exists?(cartfile)
            temp_file = Tempfile.new('foo')
            begin
                File.open(cartfile, 'r') do |file|
                    file.each_line do |line|
                        if line.include? "EricssonBroadcastServices/"
                            temp_file.puts line.gsub('"master"',"== "+version)
                            else
                            temp_file.puts line
                        end
                    end
                end
                temp_file.close
                FileUtils.mv(temp_file.path, cartfile)
                ensure
                temp_file.close
                temp_file.unlink
            end
        end
    end
    
    desc "Checkout latest dependencies as declared in Cartfile.resolved"
    private_lane :update_graph do
        cartfile = File.expand_path("..",Dir.pwd)
        
        sh "cd #{cartfile} carthage.sh update --use-submodules --use-xcframeworks"
#        carthage(
#                 command: "update",
#                 platform: "iOS,tvOS",
#                 use_submodules: true,
#                 use_ssh: false,
#                 use_binaries: false,
#                 no_build: true
#                 )
#        update_dependency_graph()
    end
    
    
    private_lane :bump_build_number do

        new_build_number = increment_build_number(xcodeproj: "iOSClientExposure.xcodeproj")
        UI.message("Build: #{new_build_number}")
        commit_version_bump(
                            message: "Build number: #{new_build_number}",
                            xcodeproj: "iOSClientExposure.xcodeproj"
                            )
    end
    
    desc "Posts a success notification for development integration"
    desc "in the Players channel on Slack"
    private_lane :notify_slack_dev_success do
        current_build_number = get_build_number
        current_time = Time.now.to_f
        project_name = ENV["PROJECT_TITLE"]
        
        changelog = changelog_from_git_commits(
                                               commits_count: 10,
                                               pretty: '• %s',
                                               merge_commit_filtering: 'exclude_merges'
                                               )
        
        UI.message(current_time)
        slack(
              use_webhook_configured_username_and_icon: true,
              default_payloads: [],
              attachment_properties: {
                    pretext: "#{project_name} build #{current_build_number} succesful!",
                    color: "good",
                    text: changelog,
                    footer: ENV["DEV_TEAM_NAME"],
                    ts: current_time,
                }
              )
    end
    
    after_all do |lane|
        # This block is called, only if the executed lane was successful
        
    end
    
    error do |lane, exception|
        
        slack(
              message: exception.message,
              success: false
              )
              
              UI.error("====> ERROR")
    end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
