# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do
    before_all do
        # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
        
        #updateDependencies
    end
    
    
    desc "Checkout latest dependencies"
    private_lane :updateDependencies do
        carthage(
                 command: "update",
                 platform: "iOS",
                 use_submodules: true,
                 use_ssh: true,
                 use_binaries: false
                 )
    end
    
    
    desc "Bumps build number and runs unit tests on each push to development branch"
    desc "If successful, "
    lane :manage do
        ensure_git_branch(branch: "development")
        
        #ensure_git_status_clean
        
        bump_build_number
        
        runUnitTests
        
    end
    
    
    desc "Runs all the tests"
    lane :runUnitTests do
        
        scan(
             workspace: "Exposure.xcworkspace",
             scheme: "Exposure"
             )
             
        UI.success("====> TESTING DONE")
    end
    
    
    # Private lanes
    
    private_lane :bump_build_number do
        new_build_number = increment_build_number(xcodeproj: "Exposure.xcodeproj")
        UI.message("Build: #{new_build_number}")
        commit_version_bump(
                            message: "Build number bumped: #{new_build_number}",
                            xcodeproj: "Exposure.xcodeproj"
                            )
    end
    
    
    after_all do |lane|
        # This block is called, only if the executed lane was successful
        
        # slack(
        #   message: "Successfully deployed new App Update."
        # )
    end
    
    error do |lane, exception|
        
        #slack(
        #   message: exception.message,
        #   success: false
        # )
        
        UI.error("====> ERROR")
    end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
