name: Test on iOS /tvOS  platforms

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build:

    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        xcode: ['13.0']
        scheme: ['iOSClientExposure']
        command: ['test']
        platform: ['iOS', 'tvOS']

    steps:
    - uses: actions/checkout@v3
    - name: Show eligible build destinations for iOSClientExposure
      run: xcodebuild -showdestinations -scheme iOSClientExposure
    - name: Build iOS ( iOS 15.0)
      run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
    - name: Build tvOS ( tvOS 15.0)
      run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk appletvsimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-tvos13.0-simulator"
    - name: Run tests - iOS
      run: swift test -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
    - name: Run tests
      run: swift test -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk appletvsimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-tvos13.0-simulator"

